-- 
-- VentasDW | OLTP V1: esquema transaccional de ventas  
 

CREATE FUNCTION set_updated_at() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
    NEW.updated_at := now();
    RETURN NEW;
END;
$$;

CREATE TABLE ciudad (
    ciudad_id     integer      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ciudad        varchar(80)  NOT NULL,
    provincia     varchar(80)  NOT NULL,
    departamento  varchar(80)  NOT NULL,
    pais          varchar(80)  NOT NULL DEFAULT 'Peru',
    updated_at    timestamptz  NOT NULL DEFAULT now()
);

CREATE TABLE categoria (
    categoria_id  integer      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre        varchar(100) NOT NULL UNIQUE,
    updated_at    timestamptz  NOT NULL DEFAULT now()
);

CREATE TABLE cliente (
    cliente_id  integer      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre      varchar(200) NOT NULL,
    email       varchar(254),
    ciudad_id   integer      REFERENCES ciudad (ciudad_id),
    updated_at  timestamptz  NOT NULL DEFAULT now()
);

CREATE TABLE empleado (
    empleado_id  integer      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre       varchar(200) NOT NULL,
    cargo        varchar(100),
    updated_at   timestamptz  NOT NULL DEFAULT now()
);

CREATE TABLE producto (
    producto_id    integer       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre         varchar(200)  NOT NULL,
    categoria_id   integer       REFERENCES categoria (categoria_id),
    precio_lista   numeric(12,2),
    descontinuado  boolean       NOT NULL DEFAULT false,
    updated_at     timestamptz   NOT NULL DEFAULT now()
);

CREATE TABLE pedido (
    pedido_id     bigint       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cliente_id    integer      REFERENCES cliente (cliente_id),
    empleado_id   integer      REFERENCES empleado (empleado_id),
    fecha_pedido  date         NOT NULL,
    estado        varchar(40)  NOT NULL DEFAULT 'PENDIENTE',
    updated_at    timestamptz  NOT NULL DEFAULT now()
);

CREATE TABLE detalle_pedido (
    pedido_id        bigint        NOT NULL REFERENCES pedido (pedido_id),
    linea            integer       NOT NULL,
    producto_id      integer       REFERENCES producto (producto_id),
    cantidad         integer,
    precio_unitario  numeric(12,2),
    descuento        numeric(5,4)  DEFAULT 0,
    PRIMARY KEY (pedido_id, linea)
); 
CREATE TRIGGER trg_ciudad_updated    BEFORE UPDATE ON ciudad    FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_categoria_updated BEFORE UPDATE ON categoria FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_cliente_updated   BEFORE UPDATE ON cliente   FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_empleado_updated  BEFORE UPDATE ON empleado  FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_producto_updated  BEFORE UPDATE ON producto  FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_pedido_updated    BEFORE UPDATE ON pedido    FOR EACH ROW EXECUTE FUNCTION set_updated_at();
 
CREATE FUNCTION touch_pedido() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
    IF TG_OP = 'DELETE' THEN
        UPDATE pedido SET updated_at = now() WHERE pedido_id = OLD.pedido_id;
    ELSE
        UPDATE pedido SET updated_at = now() WHERE pedido_id = NEW.pedido_id;
    END IF;
    RETURN NULL;
END;
$$;
CREATE TRIGGER trg_detalle_touch_pedido
    AFTER INSERT OR UPDATE OR DELETE ON detalle_pedido
    FOR EACH ROW EXECUTE FUNCTION touch_pedido();
 
CREATE INDEX ix_pedido_updated     ON pedido   (updated_at);
CREATE INDEX ix_pedido_cliente     ON pedido   (cliente_id);
CREATE INDEX ix_pedido_fecha       ON pedido   (fecha_pedido);
CREATE INDEX ix_cliente_updated    ON cliente  (updated_at);
CREATE INDEX ix_producto_updated   ON producto (updated_at);
CREATE INDEX ix_empleado_updated   ON empleado (updated_at);
CREATE INDEX ix_detalle_producto   ON detalle_pedido (producto_id);
