--  
-- VentasDW | V2: tablas de dimensiones


--  DIM_FECHA
CREATE TABLE dwh.dim_fecha (
    fecha_key          integer     PRIMARY KEY,                 -- yyyymmdd
    fecha              date        NOT NULL UNIQUE,
    anio               smallint    NOT NULL,
    trimestre          smallint    NOT NULL CHECK (trimestre BETWEEN 1 AND 4),
    mes                smallint    NOT NULL CHECK (mes BETWEEN 1 AND 12),
    nombre_mes         varchar(12) NOT NULL,
    anio_mes           integer     NOT NULL,                    -- yyyymm para ordenar y agrupar
    dia                smallint    NOT NULL CHECK (dia BETWEEN 1 AND 31),
    dia_semana         smallint    NOT NULL CHECK (dia_semana BETWEEN 1 AND 7),  -- ISO: 1 = lunes
    nombre_dia_semana  varchar(12) NOT NULL,
    es_fin_de_semana   boolean     NOT NULL,
    CONSTRAINT ck_dim_fecha_key CHECK (fecha_key = anio * 10000 + mes * 100 + dia)
);
COMMENT ON TABLE dwh.dim_fecha IS 'Dimensión de fecha. Estática, precargada. Jerarquía: año > trimestre > mes > día.';

--  DIM_PRODUCTO
CREATE TABLE dwh.dim_producto (
    producto_key    integer      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    producto_id     integer      NOT NULL,  
    producto        varchar(200) NOT NULL,
    categoria       varchar(100) NOT NULL,
    hash_atributos  char(32)     NOT NULL,                     
    vigente_desde   date         NOT NULL,
    vigente_hasta   date         NOT NULL DEFAULT DATE '9999-12-31',
    es_actual       boolean      NOT NULL DEFAULT true,
    CONSTRAINT ck_dim_producto_vigencia CHECK (vigente_desde < vigente_hasta),
    CONSTRAINT ck_dim_producto_actual   CHECK (es_actual = (vigente_hasta = DATE '9999-12-31')),
    CONSTRAINT ex_dim_producto_sin_solape
        EXCLUDE USING gist (producto_id WITH =, daterange(vigente_desde, vigente_hasta, '[)') WITH &&)
);
CREATE UNIQUE INDEX ux_dim_producto_actual ON dwh.dim_producto (producto_id) WHERE es_actual;
CREATE INDEX ix_dim_producto_categoria     ON dwh.dim_producto (categoria);
COMMENT ON TABLE dwh.dim_producto IS 'Dimensión de producto. SCD tipo 2. Jerarquía: categoría > producto.';

--  DIM_CLIENTE
CREATE TABLE dwh.dim_cliente (
    cliente_key     integer      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cliente_id      integer      NOT NULL,                   
    cliente         varchar(200) NOT NULL,
    email           varchar(254),
    hash_atributos  char(32)     NOT NULL,                     
    vigente_desde   date         NOT NULL,
    vigente_hasta   date         NOT NULL DEFAULT DATE '9999-12-31',
    es_actual       boolean      NOT NULL DEFAULT true,
    CONSTRAINT ck_dim_cliente_vigencia CHECK (vigente_desde < vigente_hasta),
    CONSTRAINT ck_dim_cliente_actual   CHECK (es_actual = (vigente_hasta = DATE '9999-12-31')),
    CONSTRAINT ex_dim_cliente_sin_solape
        EXCLUDE USING gist (cliente_id WITH =, daterange(vigente_desde, vigente_hasta, '[)') WITH &&)
);
CREATE UNIQUE INDEX ux_dim_cliente_actual ON dwh.dim_cliente (cliente_id) WHERE es_actual;
COMMENT ON TABLE dwh.dim_cliente IS 'Dimensión de cliente. SCD tipo 2.';

--  DIM_GEOGRAFIA
CREATE TABLE dwh.dim_geografia (
    geografia_key  integer      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ciudad_id      integer      NOT NULL UNIQUE,                -- clave natural (OLTP)
    pais           varchar(80)  NOT NULL,
    departamento   varchar(80)  NOT NULL,
    provincia      varchar(80)  NOT NULL,
    ciudad         varchar(80)  NOT NULL
);
CREATE INDEX ix_dim_geografia_depto ON dwh.dim_geografia (pais, departamento);
COMMENT ON TABLE dwh.dim_geografia IS 'Dimensión geográfica (ciudad del cliente). SCD tipo 1. Jerarquía: país > departamento > provincia > ciudad.';

--   DIM_EMPLEADO
CREATE TABLE dwh.dim_empleado (
    empleado_key  integer      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    empleado_id   integer      NOT NULL UNIQUE,                 -- clave natural (OLTP)
    empleado      varchar(200) NOT NULL,
    cargo         varchar(100)
);
COMMENT ON TABLE dwh.dim_empleado IS 'Dimensión de empleado (vendedor). SCD tipo 1.';

--   DIM_CANAL
CREATE TABLE dwh.dim_canal (
    canal_key  smallint    PRIMARY KEY,                         -- fija, no identity
    codigo     varchar(20) NOT NULL UNIQUE,
    canal      varchar(50) NOT NULL
);
COMMENT ON TABLE dwh.dim_canal IS 'Dimensión de canal de venta. Estática (Tienda, Online).';
