global:
  scrape_interval: 15s

scrape_configs:
  - job_name: etl-service
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["etl-service:8081"]

  - job_name: olap-api
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["olap-api:8080"]

  - job_name: oltp-generator
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["oltp-generator:8082"]